### PR TITLE
Added TryIntoJs for Options

### PR DESCRIPTION
**Pull request by simlay**
I want this in some stuff for fluvio-client-node.

### CODE REVIEW

**Comment by simlay** [comment]
@sehz Thoughts?

**Review by sehz — CHANGES_REQUESTED** [review]
Looks good.

Can you add this to CHANGELOG?

**Comment by sehz** [comment]
From #33, I think None should return undefined rather than null

**Comment by sehz** [comment]
In #33, None returns undefined but I agree as in this PR, it should return null

**Comment by simlay** [comment]
> Looks good.
> 
> Can you add this to CHANGELOG?

Done. I also updated the formatting on the headers. Here's [the `CHANGELOG` rendered.](https://github.com/simlay/node-bindgen/blob/try-into-js-for-option-t/CHANGELOG.md)

**Comment by sehz** [comment]
Great!

**Pull request merged**
