### PR TITLE
[Merged by Bors] - Pr prepare release 5.1

### PR DESCRIPTION
**Pull request by marcmo**
* Fix clippy warnings
* Update readme
* Update release notes

### CODE REVIEW

**Comment by sehz** [comment]
Looks good, is this ready?

**Comment by marcmo** [comment]
ready from my side yes.
things left to do:
* upload new version to crates.io (check with `cargo publish --dry-run`, then do a `cargo publish`)

**Review by EstebanBorai — APPROVED** [review]

**Comment by marcmo** [comment]
any updates on this?

**Comment by sehz** [comment]
@simlay can you publish new version?

**Comment by sehz** [comment]
more clippy failures due to new release

**Comment by simlay** [comment]
[node-bindgen 5.1.0](https://crates.io/crates/node-bindgen/5.1.0) published!

**Pull request closed without merging**
