### PR TITLE
Consider undefined/null for optional rust types (close #278)

### LINKED ISSUE #278: Support of options
## Issue

Looks like supporting of option type (`Option<T>`) isn't fully implemented.

Rust code
```
use node_bindgen::derive::node_bindgen;

#[node_bindgen]
fn test(a: Option<i32>, b: Option<i32>) -> i32 {
    a.unwrap_or(b.unwrap_or(1))
}
```
On JS side I'm expecting to do as well:
```
console.log(nativeModuleRef.test(100,200)); // OK
console.log(nativeModuleRef.test(200)); // OK
console.log(nativeModuleRef.test(null, 300)); // FAIL
console.log(nativeModuleRef.test(200, null));// FAIL
console.log(nativeModuleRef.test(undefined, 300)); // FAIL
console.log(nativeModuleRef.test(undefined, undefined));// FAIL
console.log(nativeModuleRef.test()); // OK
```

For example from `serde_json` perspective `Option::None` equal to `undefined` and `null` as well. Parsing goes without issues and with `undefined` and with `null` and without definition of value on js-object.

## Reproducing

I'm also attaching sources of working example.
```
# unpack
cd node-bindgen_issue_options
nj-cli build --release
node ./dist/lib.js
```

## Suggestion
Value `Option::None` should have an equivalent on JS side - `null` and `undefined` as well. "From" rust world to JS world `Option::None` should be returned as `null`. Well in general my suggestion just to fit `serde_json`

[node-bindgen_issue_options.zip](https://github.com/infinyon/node-bindgen/files/13370610/node-bindgen_issue_options.zip)

Many thanks in advance for your feedback.

### PR DESCRIPTION
**Pull request by DmitryAstafyev**
Before parsing value from JS and converting it into rust-type, checking for `null` / `undefined` and consider it as `Option<T>`

### CODE REVIEW

**Comment by DmitryAstafyev** [comment]
related to #278

**Comment by morenol** [comment]
@DmitryAstafyev can you rebase on #281 is merged?

Can we add a new test/example for this case?

**Comment by DmitryAstafyev** [comment]
> @DmitryAstafyev can you rebase on #281 is merged?
> 
> Can we add a new test/example for this case?

done

**Comment by DmitryAstafyev** [comment]
@morenol tests are green )

**Comment by DmitryAstafyev** [comment]
@morenol 
> Can we add a new test/example for this case?
Sorry, missed this question. I guess, yes... give me a try

**Comment by DmitryAstafyev** [comment]
@morenol test has been added. Test has been passed ) we are green

**Review by morenol — APPROVED** [review]
nice! LGTM!

**Review by sehz — APPROVED** [review]
LGTM.  Good job

**Pull request merged**
