### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by palfrey**
~~Primarily this enables Travis builds on a combination of Rust versions, Node.js versions and Linux + OSX. Along the way,~~ I've found/fixed a few issues

* #6 seems to have actually broken OSX support. I've fixed the fix, and also fixed a related item in nj-cli that made it not work on non-Macs
* There was a couple of usages of Rust-style `{}` format specifiers in the Node code, which I've replaced with `%s`
* Streams example had a `#![feature(prelude_import)]` which a) only worked on nightly Rust builds b) didn't appear to be needed anymore, so I've removed it. The streams test sometimes wasn't waiting long enough, so I've made it wait a bit longer.

~~There's a couple of commented out builds in the `.travis.yml` which don't fully work yet. I suspect they're because the checked in bindgen file in `nj-sys` needs regenerating on build, but I haven't fixed that yet.~~

~~There's also a build badge. It currently points to my repo, and you'll need to [activate this repository in Travis](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github) and then switch over the URLs. See https://travis-ci.com/github/palfrey/node-bindgen/builds/158166702 for currently working build on my repo.~~

### CODE REVIEW

**Comment by sehz** [comment]
Otherwise, everything else looks good

**Comment by palfrey** [comment]
> I see link to your personal travis configuration.

Yup, that was intended more as a placeholder so there was a link to a config at all before you enabled it for this repository and it got switched over.

> I think for CI, probably choose GitHub actions

I think Travis is actually a better choice in this case, as the OSX support in Github Actions is limited. It only supports 10.15, as opposed to Travis which supports all the way back to 10.10 if that's of any interest. The build file I've submitted tests on both 10.13 and 10.14 (and eventually they'll have 10.15 support...)

**Comment by sehz** [comment]
For now, can you make separate pull request for Travis?.

I have created separate issue: https://github.com/infinyon/node-bindgen/issues/8 for CI pipeline.  We can discuss pros/cons.  If Travis is selected, can accept that pull request

**Comment by palfrey** [comment]
> For now, can you make separate pull request for Travis?

Done as #11 

> I have created separate issue: #8 for CI pipeline. We can discuss pros/cons. If Travis is selected, can accept that pull request.

Ok.

**Pull request merged**
