### PR TITLE
Feature/ci/publish

### PR DESCRIPTION
**Pull request by Ryanmtate**
This PR runs the following steps on push to `release` (e.g. successful PR merge)

Added to the CI workflow:
1. Checks out the branch, checks if the version is fresh;

Adds a release workflow:
1. Builds the latest tagged version; Requires pushing a tagged release `v*`;
2. Releases the newly built tagged version;
3. Publishes on release the crate to crates.io;

### CODE REVIEW

**Comment by Ryanmtate** [comment]
@sehz We will need to set the following secrets in the github repo settings:

- REPO_ACCESS_TOKEN
- CRATES_TOKEN

**Comment by Ryanmtate** [comment]
Look into a workflow that builds all dependency crates and publishes, in addition to the node-bindgen main crate

**Comment by Ryanmtate** [comment]
I plan on integrating https://github.com/infinyon/cargo-cvm with our CI workflow to check for version updates.

This will remove the version bumping step in the release process.

**Comment by Ryanmtate** [comment]
@sehz We can remove `REPO_ACCESS_TOKEN` from the secrets. 

CI nows makes an explicit check for the versions and requires the developer to update the semantic version of the crate. 

As a result, I have removed the bump version action that used this secret.

**Comment by sehz** [comment]
REPO_ACCESS_TOKEN removed

**Comment by Ryanmtate** [comment]
I think part of the problem here is that checkout cant find the branch to do the comparison because the branch is coming from another remote other than origin.

Might re-open this directly under Infinyon rather than through my personal.

**Comment by Ryanmtate** [comment]
`cargo cvm -x` is working now! 🎉 

This PR adds a release workflow when a tagged branch is pushed. Current this step is manual, however, once the tagged branch is pushed, the release will build `nj-cli` and package for release. Additionally, the release includes a publish to crates.io for all crates in the workspace.

**Pull request merged**
