### PR TITLE
Use bors for merging

### PR DESCRIPTION
**Pull request by nicholastmosher**
- Configure Bors for merging PRs in node-bindgen
- Cleaned up CI definition to make it easier to integrate with Bors

### CODE REVIEW

**Comment by nicholastmosher** [comment]
bors ping

**Comment by nicholastmosher** [comment]
@sehz if this CI passes, you should be able to merge this PR using `bors r+`

**Review by sehz — APPROVED** [review]

**Comment by nicholastmosher** [comment]
Hmm I wonder if the `bors.toml` needs to already be in master to work. @sehz I don't have write access on this repo, can you merge this manually for me? I think it should work after that.

**Comment by nicholastmosher** [comment]
bors ping

**Pull request merged**
