### PR TITLE
fix bug in command `nj-cli build --release`

### PR DESCRIPTION
**Pull request by garyhai**
Add "--release" argument correctly.

### CODE REVIEW

**Review by sehz — APPROVED** [review]
thanks for changes!

**Review by sehz — CHANGES_REQUESTED** [review]
bump up cargo version  so we can release updates

**Comment by garyhai** [comment]
> bump up cargo version so we can release updates

Ok. Please take care of conflicts of version number.

**Comment by sehz** [comment]
@Ryanmtate can you figure out why version check is failing?

**Comment by sehz** [comment]
I see.  0.4.0 has been never been published.  will merge this and fix version and will publish

**Comment by Ryanmtate** [comment]
> I see. 0.4.0 has been never been published. will merge this and fix version and will publish

version manager does not check against the deployed version, which is something that I can add in the future. Whenever there is a change to the `src/` directory from a previous commit and the version have not been bumped, it will throw an error when checking. The solution would be to increment the version to `0.4.1`  or to ignore the version check if you hadn't published `0.4.0` previously.

**Comment by sehz** [comment]
published 0.4.0 version of `nj-cli`.   With `--release` mode, binary size went from 8M -> 1M.

**Pull request merged**
